Cotizador/Controllers/CotizadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cotizador.Entitys;
using Cotizador.Models;
using System.Data.Entity;
using Microsoft.Reporting.WebForms;
using System.IO;


namespace Cotizador.Controllers
{
    [Security.UserFilter()]
    public class CotizadorController : Controller
    {
        CotizadorContext context = new CotizadorContext();

        public ActionResult Lista() // Lista de Contizaciones Hechas.
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult Detalle(int CotID)//Devolver el detalle correspondiente 
        {

            var detalle = context.detalleCoti.Where(x => x.idcotizacion.Equals(CotID))
                .Include(c => c.Servicios).ToList();
            return PartialView(detalle);
        }
        [HttpPost]
        public JsonResult GetCotizaciones(DataTable Table)// Obtener Todas las Cotizaciones Del Sistema.
        {
            try
            {
                var cotizador = new List<Cotizaciones>();
                int TotalRecords;
                int RecordsFiltered;
                
                //Buscar Datos:
                if (!string.IsNullOrEmpty(Table.Search.value)){

                    var fechas = Table.Search.value.Split('/');
                    var Desde = Convert.ToDateTime(fechas[0]);
                    var Hasta = Convert.ToDateTime(fechas[1]);
                    cotizador = context.cotizacion.Where(x => x.Fecha>= Desde && x.Fecha <=Hasta.Date)
                        .Include(x => x.cliente).ToList();
                }
                else
                {
                    cotizador = context.cotizacion.Include(l => l.cliente).Where(x => x.Expiracion.Date.Equals(DateTime.Now.Date) != true).ToList();
                }
                TotalRecords = cotizador.Count();
                //Ordenando los datos
                switch (Table.Order[0].column)
                {
                    case 0:
                        cotizador = (Table.Order[0].dir.Equals("asc")) ?
                            cotizador.OrderBy(x => x.id).ToList() : cotizador.OrderByDescending(x => x.id).ToList();
                        break;
                    case 1:
                        cotizador = (Table.Order[1].dir.Equals("asc")) ?
                             cotizador.OrderBy(x => x.cliente.nombre).ToList() : cotizador.OrderByDescending(x => x.cliente.nombre).ToList();
                        break;
                    case 3:
                        cotizador = (Table.Order[2].dir.Equals("asc")) ?
                            cotizador.OrderBy(x => x.Fecha).ToList() : cotizador.OrderByDescending(x => x.Fecha).ToList();
                        break;
                    case 4:
                        cotizador = (Table.Order[3].dir.Equals("asc")) ?
                            cotizador.OrderBy(x => x.Total).ToList() : cotizador.OrderByDescending(x => x.Total).ToList();
                        break;

                }

                cotizador.Skip(Table.start).Take(cotizador.Count());
                RecordsFiltered = cotizador.Count();

                return Json(new {
                    draw = Table.draw,
                    recordsTotal =TotalRecords,
                    recordsFiltered =RecordsFiltered,
                    data =cotizador
                }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                var errorList = new List<Cotizaciones>();
                return Json(new
                {
                    draw = Table.draw,
                    recordsTotal = errorList.Count,
                    recordsFiltered = errorList.Count,
                    data = errorList
                }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpGet]
        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Nuevo(string Ncliente ,string Fecha,decimal Total, DetalleCotizacion[] Detalle)
        {
            try
            {
                
                Clientes Client = context.cliente.ToList()
                    .Where(x => x.nombre.ToLower().Equals(Ncliente.ToLower())).First();
                Total+= 0.00m;

                if (Client!= null)
                {
                    //Obtener la fecha de la cotizacion convirtiendo el string en un datetime.
                    var dateData = Fecha.Split('/');
                    DateTime Date = new DateTime(Convert.ToInt32(dateData[2]),
                        Convert.ToInt32(dateData[1]), Convert.ToInt32(dateData[0]));

                    Cotizaciones cotizador = new Cotizaciones
                    {
                        idcliente = Client.id,
                        Total = Total,
                        Fecha = Date,
                        Estado = "REALIZADO"
                        
                    };


                    context.cotizacion.Add(cotizador);
                    context.SaveChanges();
                    int CotiID = cotizador.id;


                    for (int i = 0; i < Detalle.Length; i++)
                    {
                        Detalle[i].idcotizacion = CotiID;
                        Detalle[i].PrecioCotizacion += 0.00m;
                        context.detalleCoti.Add(Detalle[i]);
                    }

                    context.SaveChanges();

                    return Json(new { Mensaje = "La Cotizacion fue Creada Correctamente", Error = false }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    return Json(new
                    { Mensaje = "Error: No Se Encontro el Cliente En la Base De Datos", Error = false }, JsonRequestBehavior.AllowGet);
                }
                


                
            }
            catch(Exception ex)
            {
                return Json(new {Mensaje= "Error Encontrado: "+ ex.Message, Error=true }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult BuscarClientes(string search)
        {// Buscar los Clientes A Seleccionar, para la cotizacion.
            try
            {
                var clientes = context.cliente.ToList()
                    .Where(x => x.nombre.ToLower().Contains(search.ToLower())).Select(x => x.nombre)
                    .Take(5).ToArray();

               if (clientes.Length <= 0)
                {
                    string[] error = { "Sin Resultados" };
                    return Json(new { Clientes = error }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Clientes = clientes }, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                string[] error = { "Sin Resultados" };
                return Json(new {Clientes= error }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public JsonResult DatosCliente(string nombre)
        {
            try
            {
                var cliente = context.Database.SqlQuery<Clientes>("select * from Clientes where" +
                    " nombre= @nombre", new System.Data.SqlClient.SqlParameter("@nombre", nombre)).ToArray()[0];

                if (cliente != null)
                {
                    return Json(new
                    {
                        TipoCliente = cliente.TipoCliente,
                        dni = cliente.DNI,
                        phone = cliente.telefono,
                        direccion = cliente.direccion,
                        Error = false

                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Error = true, Mensaje = "El Cliente No Fue Encontrado" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Error = true, Mensaje = "Error Encontrado: " + ex.Message });
            }
        }
        public PartialViewResult ListaServicios()
        {

            return PartialView();
        }
        [HttpPost]
        public JsonResult Anular(int Id)
        {
            try
            {
                var model = context.cotizacion.Where(x => x.id == Id).First();
                if(model!= null)
                {
                    model.Estado = "ANULADO";
                    context.Entry(model).State = EntityState.Modified;
                    context.SaveChanges();
                    
                    return Json(new { Mensaje = "Se Anulo la Cotización correctamente", Error = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Mensaje = "No se Encontro la Cotización Seleccionada", Error = true }, JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception ex)
            {
                return Json(new { Mensaje = "Error Encontrado: "+ ex.Message, Error = true }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult Report(int id)// Devolver el pdf del Reporte de Cotizacion.
        {
            LocalReport report = new LocalReport();
            List<Entitys.ReportCotizacion> DataLists = new List<ReportCotizacion>();
            string path = Path.Combine(Server.MapPath("~/Reports"), "Coti.rdlc");

            if (System.IO.File.Exists(path))
            {
                report.ReportPath = path;
            }
            else
            {
                return RedirectToAction("Lista");
            }
            //Solicitar los datos al servidor por medio de un procedimiento almacenado
            DataLists = context.Database.SqlQuery<ReportCotizacion>("EXEC ReportCotizacion @idcotizacion",

Cotizador/Views/Cotizador/Detalle.cshtml
<!--View para mostrar el Detalle De la Cotizacion-->
@model IEnumerable<Cotizador.Models.DetalleCotizacion>
<h1 class="text-center">Detalle de Cotizacion</h1>
<br />
<p class="text-primary">Todos Los Detalles Correpondiente a esta Cotización</p>
<table class="table table-hover" id="Table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Servicio
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Costo
            </th>

        </tr>
    </thead>
    <tbody>
       @foreach(var item in Model)
       {
           <tr>
               <th>@item.id</th>
               <th>@item.Servicios.nombre</th>
               <th>@item.cantidad</th>
               <th>@item.PrecioCotizacion</th>
           </tr>
       }

    </tbody>
</table>

Cotizador/Views/Cotizador/Lista.cshtml
@{
    ViewBag.Title = "Lista de Cotizaciones";
}

<h2 class="text-primary text-center"><I class="fas fa-file-alt"></I>Lista De Cotizaciones</h2>
<div class="container-fluid">
    <button class="btn btn-primary" onclick="CotrollerNuevo()" ><i class="fas fa-plus"></i> Nueva Cotizacion</button>
    
</div>
<!--Cuadro de busqueda por fechas-->
<div class="container-fluid">
    <br />
    <label class="text-primary">Buscar Entre Fechas:</label>
    <div class="row">      
        <div class="col-md-3">
            <label>Desde: </label>
            <input type="date" class="form-control" id="Date1" />
        </div>
        <div class="col-md-3">
            <label>Hasta: </label>
            <input type="date" class="form-control" id="Date2" />
        </div>
    </div>
</div>
<br />
<div class="container-fluid">
    <table class="table table-hover" id="Coti">
        <thead>
            <tr>
                <th>ID</th>
                <th>Cliente</th>
                <th>Fecha</th>
                <th>Expiración</th>
                <th>Total</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

</div>

<!--Pantalla Modal-->
<div class="modal fade" id="CotizacionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-light" id="modaltitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="CloseModal()" disabled>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalBody">
                <h1 class="text-center">Cargando...</h1>
            </div>
            <div class="modal-footer" id="PieModal">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnsecundary"><i class="fas fa-times"></i> Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnprimary" onclick="CloseModal()"><i class="fas fa-check"></i> Finalizar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Operations/Cotizaciones.js"></script>
<script>
    MostrarTabla('@Url.Action("GetCotizaciones","Cotizador")');

    function CotrollerNuevo() {
        window.location.href = "/Cotizador/Nuevo";
    }
    </script>    
    
}

Cotizador/Views/Cotizador/ListaServicios.cshtml
<h1 class="text-center">Lista de Servicios</h1>
<br />
<p class="text-primary">Seleccione El Servicio para Agregar</p>
<table class="table table-hover" id="Table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
            <th>
                Descripcición
            </th>
            <th>
                Costo
            </th>

        </tr>
    </thead>
</table> 
<!--Script Inicializador-->
<script src="~/Scripts/Operations/Cotizaciones.js"></script>
<script> 
    var table = $("#Table");
    $(document).ready(function () {

        table = table.DataTable({
            "language": {
                "search": "Buscar",
                "searchPlaceholder": "Buscar Por Nombre",
                "lengthMenu": "Mostrando _MENU_ Por Pagina",
                "zeroRecords": "No Se Encontraron Registros",
                "infoEmpty": "No Hay Registros Para Mostrar",
                "info": "Mostrando Pagina _PAGE_ De _PAGES_",
                "processing": "Cargando Datos, Espere..",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anteriror"
                },
                "infoFiltered": "Filtrado Desde _MAX_ Registros Totales"



            },
            "processing": true,
            "serverSide": true,
            "searching": true,
            "ajax": {
                "url": "/Servicios/GetServices/",
                "type": "POST",
                "datatype": "json",
            },
            "info": true,
            "columns": [
                { title: "ID", "data": "id" },
                { title: "Nombre", "data": "nombre" },
                { title: "Descripcición", "data": "Descripcion" },
                { title: "Costo", "data": "Costo" }

            ]

        });
        
        $("#Table tbody").on("click", "tr", function () {

            $("#Table tbody tr").each(function () {

                if ($(this).hasClass("table-active")) {

                    $(this).removeClass("table-active");
                }
            });

            $(this).addClass("table-active");
            $("#btnprimary").attr("disabled", false);
            $("#DeleteRow").attr("disabled", false);

            var datos = table.row(this).data();

            SelectServicio(datos);
            
            });
           

        
    });
</script>

Cotizador/Views/Cotizador/Nuevo.cshtml
@{
    ViewBag.Title = "Nueva Cotizacion";
}
<h2 class="text-primary text-center"><i class="fas fa-file-alt"></i> Nueva Cotización</h2>

<div class="container">
    <div class="card"><!--Contenedor de los Elementos-->
        <div class="card-header">
            <label class="text-center">Datos Del Cliente:</label> 
        </div>
        <div class="card-body">
            <div class="row"><!--Datos del Cliente-->
                <div class="col-lg-3">
                    <label>Cliente: </label>
                    <input type="text" class="form-control" id="BuscarCliente" placeholder="Ingrese Un Cliente"/>
                </div>
                <div class="col-lg-3">
                    <label>Tipo De Cliente:</label>
                    <input type="text" class="form-control" id="TipoCliente" placeholder="Tipo Cliente" readonly/>
                </div>
                <div class="col-lg-3">
                    <label> Identificación:</label>
                    <input type="text" class="form-control" id="NumIdentidad" placeholder="Identificación" readonly />
                </div>
                <div class="col-lg-3">
                    <label> Telefono:</label>
                    <input type="text" class="form-control" id="Telefono" placeholder="Telefono" readonly />
                </div>
            </div>
            <div class="row"><!--Nueva Fila-->

                <div class="col-lg-8">
                    <label>Dirección: </label>
                    <input type="text" class="form-control" id="Direccion" placeholder="Dirección" readonly/>
                </div>
            </div>
        </div>
    </div>
    <br /> <!--Seccion Para Agregar Productos O Servicios-->
    <div class="card">
        <div class="card-header">
            <label>Detalle de la Cotizacion: </label>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-3">
                    <label>Fecha de Expiración:</label>
                    <input type="date" class="form-control" id="Expiracion" />
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-2">
                    <button class="btn btn-primary" data-target="#ServiciosModal" data-toggle="modal" onclick="VerServicios()"><i class="fas fa-plus"></i> Agregar Servicio</button>
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-danger" onclick="EliminarFila()" id="DeleteRow" disabled><i class="fas fa-times"></i> Eliminar Servicio</button>
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-secondary" onclick="GuardarCotizacion()" id="CreateCoti" disabled><i class="fas fa-check-circle"></i> Crear Cotizacion</button>
                </div>
                <div class="col-lg-2">
                    <p class="text-lg-right"><strong id="Total">Total: </strong></p>
                </div>
            </div>
            <br />
            <div>
                <table class="table table-hover" id="Cotizacion">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Cantidad</th>
                            <th>Descripción</th>
                            <th>Precio Unitario</th>
                            <th>ITBIS</th>
                            <th id="total">Total</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--Pantalla Modal-->
<div class="modal fade" id="ServiciosModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-light" id="modaltitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="CloseModal()" disabled>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalBody">
                <h1 class="text-center">Cargando...</h1>
            </div>
            <div class="modal-footer" id="PieModal">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"  id="btnsecundary"><i class="fas fa-times"></i> Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnprimary" onclick="CloseModal()"><i class="fas fa-check"></i> Finalizar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script src="~/Scripts/Operations/Cotizaciones.js"></script>
}